project:
  type: "website"
  title: "Development Economics (Fall 2026)"
  output-dir: _site
  render: # Add here all folders that should be rendered
    - "index.qmd"
    - "content/index.qmd"
    - "content/tutorials.qmd"
    - "content/material/*.qmd"
    - "content/material/session*/*.qmd"
    - "content/tutorials/*.qmd"
    - "content/tutorials/*/*.qmd"

website:
  title: "Development Economics" # Title of website shown on top left
  page-navigation: true
  reader-mode: true
  open-graph: true
  favicon: "figures/icons/course_favicon.png"
  search:
    location: navbar
    type: textbox
  sidebar:
    style: docked
    contents:
      - href: index.qmd
        text: "🏠 Home"
      - href: content/index.qmd
        text: "🏢 Getting Started"
      - section: "🗓️ Material"
        contents:
          - href: content/material/index.qmd
            text: Overview
          - href: content/material/SeminarDescription.qmd
            text: Seminar Description
          - href: content/material/s_01_Intro.qmd
            text: "Session 1: Introduction"
          - href: content/material/s_02_Measuring.qmd
            text: "Session 2: Measuring Development"
          - href: content/material/s_03_HumanDev.qmd
            text: "Session 3: Human Development"
          - href: content/material/s_04_GrowthModels.qmd
            text: "Session 4: Classical and Neoclassical Growth Models"
          - href: content/material/s_05_Institutions1.qmd
            text: "Session 5: Institutional Economics I"
          - href: content/material/s_06_Institutions2.qmd
            text: "Session 6: Institutional Economics II"
          - href: content/material/s_07_Marxism.qmd
            text: "Session 7: Marxist Theories"
          - href: content/material/s_08_Dependency.qmd
            text: "Session 8: Global Political Economy"
          - href: content/material/s_09_Technology.qmd
            text: "Session 9: Technology Gaps & Complexity"
          - href: content/material/s_10_Sustainability.qmd
            text: "Session 10: Sustainable Development & Degrowth"
          - href: content/material/s_12_Summary.qmd
            text: "Session 12: Summary & Open Questions"
          - href: content/tutorials.qmd
            text: "💻 Tutorials"

  navbar:
    background: primary
  page-footer:
    background: light
    left: "Copyright 2026, Claudius Gräbner-Radkowitsch"

bibliography: references/references.bib
csl: references/jepp.csl

format:
  html:
    author-meta: Claudius Gräbner-Radkowitsch
    author:
      name: Claudius Gräbner-Radkowitsch
      url: https://claudius-graebner.com/
      orcid: 0000-0003-4065-4722
      affiliation: EUF and JKU
      affiliation-url: https://www.uni-flensburg.de/en/pluralist-economics
    date-format: "DD MM YYYY"

    email-obfuscation: javascript
    link-external-newwindow: true
    link-external-icon: false
    code-fold: true
    code-tools: true
    code-copy: true
    highlight-style: github

    theme:
      light: 
        - cosmo
        - assets/styles/custom.scss # Change the default colour
    toc: true

execute:
  freeze: auto

