---
title: "Material overview"
---

## 📚 General references

- [Developing Economics Blog](https://developingeconomics.org/): a critical blog on development topics
- [Hierarchies of Development Podcast](https://www.eadi.org/news/podcast-hierarchies-of-development): critical podcast with very interesting, longer interviews about specific development topics
- [Our World in Data](https://ourworldindata.org/): huge collection of data, together with a blog that is usually in the progressive-mainstream direction

## 🔖 Session-specific material




| Session | Topic                                                                                                  |
|:-------:|:-------------------------------------------------------------------------------------------------------|
|    1    | [Introduction and the meaning of 'development'](/content/material/s_01_Intro.qmd)                       |
|    2    | [Measuring Development](/content/material/s_02_Measuring.qmd)                                               |
|    3    | [Human Development and the Capabilities Approach](/content/material/s_03_HumanDev.qmd)                     |
|    4    | [Classical and Neoclassical Growth Models](/content/material/s_04_GrowthModels.qmd)                            |
|    5    | [Institutional Economics and Development I](/content/material/s_05_Institutions1.qmd)                           |
|    6    | [Institutional Economics and Development II](/content/material/s_06_Institutions2.qmd)                          |
|    7    | [Marxist Theories of Development](/content/material/s_07_Marxism.qmd)                                     |
|    8    | [Dependency Theory](/content/material/s_08_Dependency.qmd)                                           |
|    9    | [Technology Gaps, Innovation Systems, and Economic Complexity](/content/material/s_09_Technology.qmd) |
|   10    | [Sustainable Development, Environmental Limits, and Degrowth](/content/material/s_10_Sustainability.qmd)         |
|   12    | [Summary and Open Questions](/content/material/s_12_Summary.qmd)                                     |


