---
title: "🗓️ Session 1: Introduction and the meaning of 'development'"
date: "2026-09-18"
date-modified: last-modified
---

## Abstract

In this introductory lecture we discuss four "grand theories" that all give different answers to the question of "What is development?".
As we will see throughout this course, the fundamental ideas of these four approaches continue to shape - implicitly or explicitly - the discourses about the rights and wrongs of development policy.

## 🖥️ Lecture Slides 

Either click on the slide area below or click 
[here](slides/DevEcon26_L01_MeaningDevelopment.pdf) to download the slides.

```{=html}
<div class="embed-container">
  <iframe 
  src="/content/material/slides/DevEcon26_L01_MeaningDevelopment.pdf" 
  style="border: 0.5px" 
  width="80%"
  height="80%"
  ></iframe>
</div>
```


## 📚 Follow-up Reading

- Snapshot of the Human Development Report [-@undp2024]
- Chang [-@chang2011]
- Chapter 1 in Escobar [-@escobar1995]

### 🏆 Further readings

- Chapter 1 in Todaro and Smith [-@todaro2020]
- Chapter 1 in De Janvry and Sadoulet [-@dejanvry2021]

## ✍️ Coursework

- Add your thoughts on the following questions to the Notepad on Moodle:
  1. What do you remember as the key message of the four theories/approaches introduced?
  2. What kind of socio-ecological challenges come to your attention or are obscured if you take one of the perspectives?
  3. What are aspects that you particularly like/disagree with?
- If you have questions or problems, please post them in the [Moodle](https://elearning.uni-flensburg.de/moodle/course/view.php?id=16258) forum
