---
title: "🗓️ Session 2: Measuring Development"
date: "2026-09-25"
date-modified: last-modified
---

## Abstract

While the first session focused on the theory of development, this session focuses on its practice—or, more precisely, its measurement. We will discuss how the theoretical construct of "development" can be operationalized and measured. This includes a debate about the theory-ladenness of observations, i.e., the fact that every observation and every measurement is dependent on certain theories and theoretical commitments. Therefore, the topics of this session and the first session are inextricably linked: discussing the definition of development and its measurement must always go hand in hand.

## 🖥️ Lecture Slides 

There are no slides for this lecture.

## 📚 Mandatory Reading

- Tutorial on [Important measures of development](../tutorials/MeasuringDevelopment/index.qmd)

### 🏆 Further readings

- Chapter 2 in Todaro and Smith [-@todaro2020]

## ✍️ Coursework (optional)

- Choose three countries and compare their level of development using 3 different measures discussed in the [tutorial](../tutorials/MeasuringDevelopment/index.qmd)
- If you have questions or problems, please post them in the [Moodle](https://elearning.uni-flensburg.de/moodle/course/view.php?id=16258)  forum
