---
title: "🗓️ Session 4: Classical and Neoclassical growth models"
date: "2026-10-09"
date-modified: last-modified
---

## Abstract


This session examines how economists theorize the drivers of economic growth and their implications for development. We begin with classical perspectives from Smith, Ricardo, and Marx, who focused on systemic dynamics and the limits or contradictions of capitalist growth. We then explore the foundational Solow-Swan model, which introduced factor substitution and diminishing returns to explain stable growth and predict convergence between rich and poor countries.

Through growth accounting, we will see how technological change emerges as the primary driver of long-term growth, leading to endogenous growth theories that attempt to explain innovation and human capital accumulation. You will engage with empirical evidence on convergence and learn to critically evaluate what growth models reveal about development processes - and what important aspects they obscure, including distributional conflicts, institutional factors, and environmental constraints.

## 🎥 Lecture videos

The four videos are shown below. Alternatively, you can access them via this [playlist](https://youtube.com/playlist?list=PLZDawQMrG1RIJSkUgHoNuHNAzxZQ2sZc5&si=aWfpj7uqsu1Cromt) on Youtube.

```{=html}
<div class="embed-container">
<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/videoseries?si=2WqkILQ7kL0Yb3uE&amp;list=PLZDawQMrG1RIJSkUgHoNuHNAzxZQ2sZc5" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
</div>
```



## 🖥️ Lecture Slides

Either click on the slide area below or click [here](slides/DevEcon26_L04_GrowthModels.pdf) to download the slides.

```{=html}
<div class="container" style="position: relative;overflow: hidden;width: 100%;padding-top: 56.25%;">
<iframe src="slides/DevEcon26_L04_GrowthModels.pdf" style="position: absolute;top: 0;left: 0;bottom: 0;right: 0;width: 100%;height: 100%;" allowfullscreen loading="lazy"></iframe>
</div>
```

## 🎯 Exercise

- More information on the convergence exercise provided [here](/content/material/s_04_Exercise.html)
- The [Penn World Tables](https://www.rug.nl/ggdc/productivity/pwt/?lang=en)
- [Possible solution](/content/material/s_04_Solution.html)

## 📚 Mandatory Reading

- World Bank [-@worldbank2024] ([Download PDF](https://openknowledge.worldbank.org/entities/publication/7c5cd962-11ae-4101-8f3f-e15b86135f0e))

## 🏆 Further Readings

- Solow [-@solow1956] and Swan [-@swan1956]
  - The original papers introducing the fundamental growth model
- Solow [-@solow1957]
  - The original article on Solow's empirical growth accounting
- Acemoglu [-@acemoglu2017]
  - While many expositios are technically very advanced, they give a good overview about the current state of the art of the mainstream approach; chapters 2 and 3 cover the Solow-Swan model in a lot of detail 

-------

If you have questions or problems, please post them in the [Moodle](https://elearning.uni-flensburg.de/moodle/course/view.php?id=17917) forum.


## References

::: {#refs}
:::
